export const START_REQUEST = 'START_REQUEST';
export const FINISH_REQUEST = 'FINISH_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const CAPTCHA_UPDATED = 'CAPTCHA_UPDATED';
export const TOGGLE_COLLAPSED = 'TOGGLE_COLLAPSED';

export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';


